config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: 'incomes#index'
  resources :incomes, only: [:new, :create, :show, :edit, :update, :destroy] do
    collection do
      get 'search'
    end
  end
  resources :spendings, only: [:new, :create, :show, :edit, :update, :destroy] do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/income.rb
class Income < ApplicationRecord
  with_options presence: true do
    validates :price, inclusion: { in: 1..100000000 }, format: {with: /\A[0-9]+\z/}, numericality: true 
    validates :category
    validates :memo
    validates :date
  end

  def start_time
    self.date
  end




  belongs_to :user
end

app/models/spending.rb
class Spending < ApplicationRecord
  with_options presence: true do
    validates :price, inclusion: { in: 1..100000000 }, format: {with: /\A[0-9]+\z/}, numericality: true 
    validates :category
    validates :memo
    validates :date
  end

  def start_time
    self.date
  end


  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  with_options presence: true do
    validates :name
  end
  validates :password, :password_confirmation, length: { minimum: 6 }, format: { with: /(?=.*[a-zA-Z])(?=.*\d)[a-zA-Z\d]{6,}/ }

  has_many :incomes
  has_many :spendings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :authenticate_user!
  before_action :income_id, only: [:show, :edit, :update, :destroy]
  before_action :income_user, only: [:index, :search]
  before_action :spending_user, only: [:index,:search, :show]
  before_action :move_to_index, only: [:show, :edit, :destroy, :update]
  require "time"
  
  def index
    @spendings_time = Spending.where(date: Time.now.beginning_of_month..Time.now.end_of_month).where(user_id: current_user.id).order(date: "ASC")
    @incomes_time = Income.where(date: Time.now.beginning_of_month..Time.now.end_of_month).where(user_id: current_user.id).order(date: "ASC")
    @spending_sum = @spendings_time.sum(:price)
    @income_sum = @incomes_time.sum(:price)
    @expense_sum = @income_sum - @spending_sum
    @spending_data = Spending.where(date: Time.now.beginning_of_month..Time.now.end_of_month).where(user_id: current_user.id)
    @this_month = Time.new.month
  end

  def new
    @income = Income.new
  end

  def create
    @income = Income.new(income_params)
    if @income.save
      redirect_to root_path
    else 
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @income.update(income_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @income.destroy
    redirect_to root_path
  end

  def search
  end

  private
  def income_params
    params.require(:income).permit(:price, :category, :memo, :date).merge(user_id: current_user.id)
  end
  def income_id
    @income = Income.find(params[:id])
  end
  def income_user
    @incomes = Income.includes(:user).order(date: "ASC")
  end
  def spending_user
    @spendings = Spending.where(user_id: current_user.id).includes(:user).order(date: "ASC")
  end
  def move_to_index
    # if current_user.id != @income.user.id
    #   redirect_to root_path
    # end
  end
end

app/controllers/spendings_controller.rb
class SpendingsController < ApplicationController
  def new
    @spending = Spending.new
  end

  def create
    @spending = Spending.new(spending_params)
    if @spending.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @income = Income.includes(:user).order(date: "ASC")
    @spending = Spending.find(params[:id])
  end

  def edit
    @spending = Spending.find(params[:id])
  end

  def update
    @spending = Spending.find(params[:id])
    if @spending.update(spending_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @spending = Spending.find(params[:id])
    @spending.destroy
    redirect_to root_path
  end

  def search
    @income = Income.includes(:user).order(date: "ASC").where(user_id: current_user.id)
    @spendings = Spending.includes(:user).order(date: "ASC").where(user_id: current_user.id)
  end

  private
  def spending_params
    params.require(:spending).permit(:price, :category, :memo, :date).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/spendings_helper.rb
module SpendingsHelper
end

app/views/incomes/edit.html.erb
<%= render "shared/header" %>

<%= form_with model: @income, class: "new-income-form", local: true do |f| %>
<div class="form-wrap">
  <div class="form-header">
    <h1 class="form-header-text">
      <%= link_to '収入フォーム', new_income_path, class:"post-income-text" %>
    </h1>
  </div>
  <%= render 'shared/error_messages', model: f.object %>
  <div class="form-content">
    <div class="form-date">
      <label class="date-category">
        <span>日付</span>
        <%= f.date_field :date, class: 'form-control', id:"date" %>
      </label>
    </div>
    <div class="form-category">
      <div class="upper-form">
        <label class="meal-category">
          <%= image_tag 'salary.png' , size: '70x70' %>
          <span class="form-letter">給料</span>
          <%= f.radio_button :category, '給料' %>
        </label>
        <label class="daily-necessities-category">
          <%= image_tag 'pocket-money.png', size: '70x80' %>
          <span class="form-letter">おこづかい</span>
          <%= f.radio_button :category, 'おこづかい' %>
        </label>
        <label class="fashion-category">
          <%= image_tag 'bonus.png', size: '70x70' %>
          <span class="form-letter">賞与</span>
          <%= f.radio_button :category, '賞与' %>
        </label>
        <label class="hobby-category">
          <%= image_tag 'investing.png', size: '70x70' %>
          <span class="form-letter">投資</span>
          <%= f.radio_button :category, '投資' %>
        </label>
        <label class="medical-category">
          <%= image_tag 'second-business.png', size: '80x80' %>
          <span class="form-letter">副業</span>
          <%= f.radio_button :category, '副業' %>
        </label>
      </div>
      <div class="lower-form">
        <label class="entertainment-expenses-category">
          <%= image_tag 'incidental-income.png', size: '70x70' %>
          <span class="form-letter">臨時収入</span>
          <%= f.radio_button :category, '臨時収入' %>
        </label>
        <label class="etc-category">
          <%= image_tag 'etc.png', size: '70x70' %>
          <span class="form-letter">その他</span>
          <%= f.radio_button :category, 'その他' %>
        </label>
      </div>
    </div>
    <div class="form-price">
      <td>
        <%= f.text_field :price, class:"price-input", placeholder:"￥" %>
    </div>
    <div class="form-memo">
      <%= f.text_field :memo, class:"memo-input", placeholder:"memo" %>
    </div>
    <div class="form-submit">
      <%= f.submit "SEND" ,class:"submit-red-btn" %>
    </div>
  </div>
</div>
<% end %>

<%= render "shared/footer2" %>

app/views/incomes/index.html.erb
<div class="footerFixed">
  <%= render "shared/header" %>
  <div class="post-content-parent">
    <div class="post-content">
      <div class="left-content">
        <div class="title"><%= @this_month %>月の支出</div>
        <div class="post-list-content">
          <% @spendings_time.each do |spending| %>
            <ul class="post-list">
              <li class="post-list-data-date"><%= spending.date %></li>
              <ul>
                <li><%= link_to '詳細', spending_path(spending.id), class:"link_pass" %></li>
                <li><%= link_to '編集', edit_spending_path(spending.id), class:"link_pass" %></li>
                <li><%= link_to '削除', spending_path(spending.id), class:"link_pass", method: :delete %></li>
              </ul>
              <li class="post-list-data"><%= spending.category %></li>
              <li class="post-list-data"><%= image_tag 'money.png', size: '50x50' %>¥<%= spending.price %></li>
            </ul>
          <% end %>
        </div>
      </div>
      <div class="center-content">
        <div class="title"><%= @this_month %>月の収入</div>
          <div class="post-list-content">
            <% @incomes_time.each do |income| %>
              <ul class="post-list">
                <li class="post-list-data-date"><%= income.date %></li>
                <ul>
                  <li><%= link_to '詳細', income_path(income.id), class:"link_pass" %></li>
                  <li><%= link_to '編集', edit_income_path(income.id), class:"link_pass" %></li>
                  <li><%= link_to '削除', income_path(income.id), class:"link_pass", method: :delete %></li>
                </ul>
                <li class="post-list-data"><%= income.category %></li>
                <li class="post-list-data"><%= image_tag 'money.png', size: '50x50' %>¥<%= income.price %></li>
              </ul>
            <% end %>
          </div>
      </div>
      <div class="right-content">
        <div class="title"><%= @this_month %>月の収支</div>
          <div class="right-content-post">
            <div class="right-content-upper">
              <%= pie_chart @spending_data.group(:category).sum(:price), thousands: ",", width: "450px", height:"450px", class:"date-graph", library: {title: {text: "今月の支出 計 #{@spending_sum}円"}} %>
            </div>
            <div class="right-content-bottom">
              <div class="income-sum">
                今月の収入 <%= @income_sum %>円
              </div>
              <div class = "spending-sum">
                今月の出費 -<%= @spending_sum %>円
              </div>
              <div class="expense-sum">
                収支 計 <%= @expense_sum %>円
              </div>
            </div>
          </div>
      </div>
  </div>
  <%= render "shared/footer" %>
</div>

app/views/incomes/new.html.erb
<%= render "shared/header" %>

<%= form_with model: @income, class: "new-income-form", local: true do |f| %>
<div class="form-wrap">
  <div class="form-header">
    <h1 class="form-header-text">
      <%= link_to '収入フォーム', new_income_path, class:"post-income-text" %>
    </h1>
  </div>
  <%= render 'shared/error_messages', model: f.object %>
  <div class="form-content">
    <div class="form-date">
      <label class="date-category">
        <span>日付</span>
        <%= f.date_field :date, class: 'form-control', id:"date" %>
      </label>
    </div>
    <div class="form-category">
      <div class="upper-form">
        <div class="category-income-container">
          <label class="label-category">
            <%= image_tag 'salary.png' , size: '70x70' %>
            <span class="form-letter">給料</span>
            <%= f.radio_button :category, '給料', class:"radio-btn" %>
          </label>
        </div>
        <div class="category-income-container">
          <label class="daily-necessities-category">
            <%= image_tag 'pocket-money.png', size: '70x80' %>
            <span class="form-letter">おこづかい</span>
            <%= f.radio_button :category, 'おこづかい' %>
          </label>
        </div>
        <div class="category-income-container">
          <label class="fashion-category">
            <%= image_tag 'bonus.png', size: '70x70' %>
            <span class="form-letter">賞与</span>
            <%= f.radio_button :category, '賞与' %>
          </label>
        </div>
        <div class="category-income-container">
          <label class="hobby-category">
            <%= image_tag 'investing.png', size: '70x70' %>
            <span class="form-letter">投資</span>
            <%= f.radio_button :category, '投資' %>
          </label>
        </div>
        <div class="category-income-container">
          <label class="medical-category">
            <%= image_tag 'second-business.png', size: '80x80' %>
            <span class="form-letter">副業</span>
            <%= f.radio_button :category, '副業' %>
          </label>
        </div>
      </div>
      <div class="lower-form">
        <div class="category-income-container">
          <label class="entertainment-expenses-category">
            <%= image_tag 'incidental-income.png', size: '70x70' %>
            <span class="form-letter">臨時収入</span>
            <%= f.radio_button :category, '臨時収入' %>
          </label>
        </div>
        <div class="category-income-container">
          <label class="etc-category">
            <%= image_tag 'etc.png', size: '70x70' %>
            <span class="form-letter">その他</span>
            <%= f.radio_button :category, 'その他' %>
          </label>
        </div>
      </div>
    </div>
    <div class="form-price">
      <td>
        <%= f.text_field :price, class:"price-input", placeholder:"￥" %>
    </div>
    <div class="form-memo">
      <%= f.text_field :memo, class:"memo-input", placeholder:"memo" %>
    </div>
    <div class="form-submit">
      <%= f.submit "SEND" ,class:"submit-red-btn" %>
    </div>
  </div>
</div>
<% end %>

<%= render "shared/footer2" %>

app/views/incomes/search.html.erb
<%= render "shared/header" %> 
<div class="calendar-content">
  <%= month_calendar events: @spendings do |date, spendings| %>
    <%= date.day %>

    <% spendings.each do |spending| %>
      <br><%= link_to spending.category, spending_path(spending.id), class:"calendar_link" %> -<%= link_to spending.price, spending_path(spending.id) %>
    <% end %>
  <% end %>
</div>

app/views/incomes/show.html.erb
<%= render "shared/header" %>
<div class="show-content">
  <div class="show-category">
    <h1 class="show-category-name"><%= @income.category %></h1>
  </div>
  <table class="detail-table">
    <tbody>
      <tr>
        <th class="detail-column">日付</th>
        <td class="detail-value"><%= @income.date %></td>
      </tr>
      <tr>
        <th class="detail-column">金額</th>
        <td class="detail-value"><%= @income.price %></td>
      </tr>
      <tr>
        <th class="detail-column">メモ</th>
        <td class="detail-value"><%= @income.memo %></td>
      </tr>
    </tbody>
  </table>
</div>
<%= render "shared/footer3" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Expenses</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>

</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <p class="copyright">Copyright © コツコツ家計簿 All rights reserved.</p>
</footer>

app/views/shared/_footer2.html.erb
<footer class="footer2">
  <p class="copyright2">Copyright © コツコツ家計簿 All rights reserved.</p>
</footer>

app/views/shared/_footer3.html.erb
<footer class="footer3">
  <p class="copyright3">Copyright © コツコツ家計簿 All rights reserved.</p>
</footer>

app/views/shared/_header.html.erb
<header class="header_a">
  <div class="container">
    <!— ! ロゴエリア —————————— —>
    <div class="area_logo_header">
      <%= link_to 'The-Expenses', root_path, class: "title-name" %>
      <%= link_to root_path, target: "_blank" do %>
        <%= image_tag 'etc.png' , size: '70x70', class:"logo" %>
      <% end %>
      <% if user_signed_in? %>
        <%= link_to '支出', new_spending_path, class: "post" %>
        <%= link_to '収入', new_income_path, class: "post" %>
      <% end %>
    </div>
    <!— ! ナビゲーション —————————— —>
    <nav class="area_nav_header">
      <ul class="list_nav_header">
        <% if user_signed_in? %>
        <div class="user-name"><%= current_user.name %></div>
        <% end %>
        <div class="hamburger-menu">
          <input type="checkbox" id="menu-btn-check">
          <label for="menu-btn-check" class="menu-btn"><span></span></label>
          <div class="menu-content">
            <ul>
              <% if user_signed_in? %>
                <li>
                  <%= link_to 'カレンダー', search_spendings_path %>
                </li>
                <li>
                  <%= link_to 'マイページ編集', "#" %>
                </li>
                <li>
                  <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
                </li>
                <li>
                  <%= link_to 'トップページへ', root_path %>
                </li>
              <% else %>
                <li>
                  <%= link_to 'ログイン', new_user_session_path, class: "link_under_line" %>
                </li>
                <li>
                  <%= link_to '新規登録', new_user_registration_path, class: "link_under_line" %>
                </li>
                <li>
                  <%= link_to 'トップページへ', root_path %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </ul>
    </nav>
  </div>
</header>

app/views/shared/error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '<<'), calendar.url_for_previous_view, class:"previous-letter"%>
    <span class="calendar-title"><%= start_date.year %>年 <%= t('date.month_names')[start_date.month] %></span>
    <%= link_to t('simple_calendar.next', default: '>>'), calendar.url_for_next_view, class:"next-letter" %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/spendings/edit.html.erb
<%= render "shared/header" %>

<%= form_with model: @spending, class: "new-income-form", local: true do |f| %>
<div class="form-wrap">
  <div class="form-header">
    <h1 class="form-header-text">
      <%= link_to '支出フォーム', new_spending_path, class:"post-income-text" %>
    </h1>
  </div>
  <%= render 'shared/error_messages', model: f.object %>
  <div class="form-content">
    <div class="form-date">
      <label class="date-category">
        <span>日付</span>
        <%= f.date_field :date, class: 'form-control', id:"date" %>
      </label>
    </div>
    <div class="form-category">
      <div class="upper-form">
        <label class="meal-category">
          <%= image_tag 'meal.png' , size: '70x70' %>
          <span class="form-letter">食費</span>
          <%= f.radio_button :category, '食費' %>
        </label>
        <label class="daily-necessities-category">
          <%= image_tag 'daily-necessities.png', size: '70x70' %>
          <span class="form-letter">日用品</span>
          <%= f.radio_button :category, '日用品' %>
        </label>
        <label class="fashion-category">
          <%= image_tag 'fashion.png', size: '70x70' %>
          <span class="form-letter">ファッション</span>
          <%= f.radio_button :category, 'ファッション' %>
        </label>
        <label class="hobby-category">
          <%= image_tag 'hobby.png', size: '70x70' %>
          <span class="form-letter">趣味・娯楽</span>
          <%= f.radio_button :category, '趣味・娯楽' %>
        </label>
        <label class="medical-category">
          <%= image_tag 'medical.png', size: '70x70' %>
          <span class="form-letter">医療費</span>
          <%= f.radio_button :category, '医療費' %>
        </label>
      </div>
      <div class="lower-form">
        <label class="entertainment-expenses-category">
          <%= image_tag 'entertainment-expenses.png', size: '70x70' %>
          <span class="form-letter">交際費</span>
          <%= f.radio_button :category, '交際費' %>
        </label>
        <label class="tility-charges-category">
          <%= image_tag 'tility-charges.png', size: '70x70' %>
          <span class="form-letter">光熱費</span>
          <%= f.radio_button :category, '光熱費' %>
        </label>
        <label class="travel-cost-category">
          <%= image_tag 'travel-cost.png', size: '70x70' %>
          <span class="form-letter">交通費</span>
          <%= f.radio_button :category, '交通費' %>
        </label>
        <label class="etc-category">
          <%= image_tag 'etc.png', size: '70x70' %>
          <span class="form-letter">その他</span>
          <%= f.radio_button :category, 'その他' %>
        </label>
      </div>
    </div>
    <div class="form-price">
      <%= f.text_field :price, class:"price-input", placeholder:"￥" %>
    </div>
    <div class="form-memo">
      <%= f.text_field :memo, class:"memo-input", placeholder:"memo" %>
    </div>
    <div class="form-submit">
      <%= f.submit "SEND" ,class:"submit-red-btn" %>
    </div>
  </div>
</div>
<% end %>

<%= render "shared/footer2" %>

app/views/spendings/new.html.erb
<%= render "shared/header" %>

<%= form_with model: @spending, class: "new-income-form", local: true do |f| %>
<div class="form-wrap">
  <div class="form-header">
    <h1 class="form-header-text">
      <%= link_to '支出フォーム', new_spending_path, class:"post-income-text" %>
    </h1>
  </div>
  <%= render 'shared/error_messages', model: f.object %>
  <div class="form-content">
    <div class="form-date">
      <label class="date-category">
        <span>日付</span>
        <%= f.date_field :date, class: 'form-control', id:"date" %>
      </label>
    </div>
    <div class="form-category">
      <div class="upper-form">
        <label class="meal-category">
          <%= image_tag 'meal.png' , size: '70x70' %>
          <span class="form-letter">食費</span>
          <%= f.radio_button :category, '食費' %>
        </label>
        <label class="daily-necessities-category">
          <%= image_tag 'daily-necessities.png', size: '70x70' %>
          <span class="form-letter">日用品</span>
          <%= f.radio_button :category, '日用品' %>
        </label>
        <label class="fashion-category">
          <%= image_tag 'fashion.png', size: '70x70' %>
          <span class="form-letter">ファッション</span>
          <%= f.radio_button :category, 'ファッション' %>
        </label>
        <label class="hobby-category">
          <%= image_tag 'hobby.png', size: '70x70' %>
          <span class="form-letter">趣味・娯楽</span>
          <%= f.radio_button :category, '趣味・娯楽' %>
        </label>
        <label class="medical-category">
          <%= image_tag 'medical.png', size: '70x70' %>
          <span class="form-letter">医療費</span>
          <%= f.radio_button :category, '医療費' %>
        </label>
      </div>
      <div class="lower-form">
        <label class="entertainment-expenses-category">
          <%= image_tag 'entertainment-expenses.png', size: '70x70' %>
          <span class="form-letter">交際費</span>
          <%= f.radio_button :category, '交際費' %>
        </label>
        <label class="tility-charges-category">
          <%= image_tag 'tility-charges.png', size: '70x70' %>
          <span class="form-letter">光熱費</span>
          <%= f.radio_button :category, '光熱費' %>
        </label>
        <label class="travel-cost-category">
          <%= image_tag 'travel-cost.png', size: '70x70' %>
          <span class="form-letter">交通費</span>
          <%= f.radio_button :category, '交通費' %>
        </label>
        <label class="etc-category">
          <%= image_tag 'etc.png', size: '70x70' %>
          <span class="form-letter">その他</span>
          <%= f.radio_button :category, 'その他' %>
        </label>
      </div>
    </div>
    <div class="form-price">
      <%= f.text_field :price, class:"price-input", placeholder:"￥" %>
    </div>
    <div class="form-memo">
      <%= f.text_field :memo, class:"memo-input", placeholder:"memo" %>
    </div>
    <div class="form-submit">
      <%= f.submit "SEND" ,class:"submit-red-btn" %>
    </div>
  </div>
</div>
<% end %>

app/views/spendings/search.html.erb
<%= render "shared/header" %> 
<div class="calendar-content">
  <%= month_calendar events: @spendings do |date, spendings| %>
    <%= date.day %>

    <% spendings.each do |spending| %>
      <br><%= link_to spending.category, spending_path(spending.id), class:"calendar_link" %> -<%= link_to spending.price, spending_path(spending.id), class:"calendar_link_price" %>
    <% end %>
  <% end %>
</div>
<%= render "shared/footer" %>

app/views/spendings/show.html.erb
<%= render "shared/header" %>

<div class="show-content">
  <div class="show-category">
    <h1 class="show-category-name"><%= @spending.category %></h1>
  </div>
  <table class="detail-table">
    <tbody>
      <tr>
        <th class="detail-column">日付</th>
        <td class="detail-value"><%= @spending.date %></td>
      </tr>
      <tr>
        <th class="detail-column">金額</th>
        <td class="detail-value"><%= @spending.price %></td>
      </tr>
      <tr>
        <th class="detail-column">メモ</th>
        <td class="detail-value"><%= @spending.memo %></td>
      </tr>
    </tbody>
  </table>
</div>
<%= render "shared/footer3" %>